### ISSUE TITLE
Debugging & Code coverage collection ends with error

### ISSUE THREAD

**Issue by aik099** [sebastianbergmann/php-code-coverage#231]
Before it was possible to debug the PHPUnit tests and collect code coverage at same time. With latest PHP CodeCoverage versions this ends up with following error:

```
PHP Fatal error:  Uncaught exception 'PHPUnit_Framework_Error_Warning' with message 'file_exists(): Unable to find the wrapper "xdebug" - did you forget to enable it when you configured PHP?' in .../vendor/phpunit/php-code-coverage/src/CodeCoverage/Driver/Xdebug.php:110
Stack trace:
#0 [internal function]: PHPUnit_Util_ErrorHandler::handleError(2, 'file_exists(): ...', '/Volumes/web/g/...', 110, Array)
#1 .../vendor/phpunit/php-code-coverage/src/CodeCoverage/Driver/Xdebug.php(110): file_exists('xdebug://debug-...')
#2 .../vendor/phpunit/php-code-coverage/src/CodeCoverage/Driver/Xdebug.php(95): PHP_CodeCoverage_Driver_Xdebug->cleanup(Array)
#3 .../vendor/phpunit/php-code-coverage/src/CodeCoverage.php(292): PHP_CodeCoverage_Driver_Xdebug->stop()
#4 .../vendor/phpunit/phpunit/src/Framework/TestResult.php(728): PHP_CodeCoverage->stop(true, Array, Array)
#5 ... in .../vendor/phpunit/php-code-coverage/src/CodeCoverage/Driver/Xdebug.php on line 110

Process finished with exit code 255
.
```

The method, that throws the exception in `Xdebug.php` is the `cleanup`:

```php
 /**
     * @param  array $data
     * @return array
     * @since Method available since Release 2.0.0
     */
    private function cleanup(array $data)
    {
        foreach (array_keys($data) as $file) {
            if (isset($data[$file][0])) {
                unset($data[$file][0]);
            }

            if (file_exists($file)) {
                $numLines = $this->getNumberOfLinesInFile($file); // exception goes from here

                foreach (array_keys($data[$file]) as $line) {
                    if (isset($data[$file][$line]) && $line > $numLines) {
                        unset($data[$file][$line]);
                    }
                }
            }
        }

        return $data;
    }
```

**Comment by rtntdeck** [comment]
I am experiencing this issue using xdebug 2.3.2 and phpunit 4.6.1.  A fix would be greatly appreciated.

**Comment by Danack** [comment]
This caught me as well - the fix seems to be known, could you implement it please?

**Comment by sebastianbergmann** [comment]
If the fix is known then why has nobody sent a pull request?

**Comment by tarlabs** [comment]
Just created one

**Comment by rtntdeck** [comment]
Thank you.
