### ISSUE TITLE
phpdbg coverage reporting gives fatal errors as of php 7.0.7

### ISSUE THREAD

**Issue by jonnybarnes** [sebastianbergmann/php-code-coverage#441]
Even on a new larvel install using PHPUnit 5:

```shell
╭─jonny@jonny-arch in /tmp/coverage 
╰$ phpdbg -qrr vendor/bin/phpunit --coverage-text
PHPUnit 5.3.4 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 110 ms, Memory: 16.00MB

OK (1 test, 2 assertions)
[PHP Fatal error:  Cannot declare class App\Http\Controllers\Controller, because the name is already in use in /tmp/coverage/app/Http/Controllers/Controller.php on line 11]
[PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /tmp/coverage/vendor/laravel/framework/src/Illuminate/Container/Container.php:752
Stack trace:
#0 /tmp/coverage/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build('Illuminate\\Cont...', Array)
#1 /tmp/coverage/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#2 /tmp/coverage/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(154): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#3 /tmp/coverage/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler()
#4 /tmp/coverage/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\B in /tmp/coverage/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 752]
```

**Comment by jonnybarnes** [comment]
This has been fixed already in PHP master: https://bugs.php.net/bug.php?id=72284
